<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_LDKPI mempunyai dan menjalankan nilai-nil_10da88</name>
   <tag></tag>
   <elementGuidId>f4b5f159-6567-439b-85bd-ca6090f54bfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f86d15af-98d7-405a-aaea-420010c00509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LDKPI mempunyai dan menjalankan nilai-nilai organisasi sebagai berikut:</value>
      <webElementGuid>ad2c7701-a372-47e0-9964-8c91de5118fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;custom-card&quot;]/div[@class=&quot;rich-text-container&quot;]/p[1]</value>
      <webElementGuid>4c394011-61ba-4caa-8e5e-c6dba84f1740</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/p</value>
      <webElementGuid>62dea397-4189-45db-84c8-3b6a68785b52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nilai Budaya'])[2]/following::p[1]</value>
      <webElementGuid>d3f15ccc-98c6-4712-988b-99a2889f4296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nilai Budaya'])[1]/following::p[1]</value>
      <webElementGuid>38c2e0fa-8127-470f-996a-af4d9af613c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integritas'])[1]/preceding::p[1]</value>
      <webElementGuid>3ba98b39-b8d1-42ef-a922-97a96a9634cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profesionalisme'])[1]/preceding::p[1]</value>
      <webElementGuid>5f6aa06d-cfb5-484f-af1f-1ade11e36469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LDKPI mempunyai dan menjalankan nilai-nilai organisasi sebagai berikut:']/parent::*</value>
      <webElementGuid>ded776db-7de9-464a-a5b4-69aba67dd174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>2a375759-e618-434a-8789-8d38cd49052c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'LDKPI mempunyai dan menjalankan nilai-nilai organisasi sebagai berikut:' or . = 'LDKPI mempunyai dan menjalankan nilai-nilai organisasi sebagai berikut:')]</value>
      <webElementGuid>9b38e2a5-028c-40d0-a4c8-64b00d1a6a37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
