<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Masuk_sapa</name>
   <tag></tag>
   <elementGuidId>ffb2f75d-fb60-4b68-a4a8-0df7f187700c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sapa</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='sapa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b8f76b7f-a2d6-436d-95a0-ed83bec137af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sapa</value>
      <webElementGuid>74df4c7b-54d1-4b2c-b077-e2798df894c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sapadjppr.kemenkeu.go.id/file.php/50138ZBRNGXJSGZ5013732086DBA3/6117c75edb9f4_sapa_color.png</value>
      <webElementGuid>eda649b1-f39e-4eca-b039-6c11f50d7bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sapa&quot;)</value>
      <webElementGuid>a530a21e-d0de-4faa-90ca-86b5bdf352f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='sapa']</value>
      <webElementGuid>c3061f27-6433-4e9d-9e7a-02ae1a893335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://sapadjppr.kemenkeu.go.id/file.php/50138ZBRNGXJSGZ5013732086DBA3/6117c75edb9f4_sapa_color.png')]</value>
      <webElementGuid>9158360d-322a-4b9c-9130-6f26fcc45f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/img</value>
      <webElementGuid>9361b0a5-978c-4713-84bb-17bb134b4c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'sapa' and @src = 'https://sapadjppr.kemenkeu.go.id/file.php/50138ZBRNGXJSGZ5013732086DBA3/6117c75edb9f4_sapa_color.png']</value>
      <webElementGuid>15e82f8f-d4d9-4401-9728-eb591ee9272b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
