<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Peta Situs_onetidHeadbnnr0</name>
   <tag></tag>
   <elementGuidId>ef4510c1-dfbc-47ad-b2ac-0e1d227e0d2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_onetidHeadbnnr2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_onetidHeadbnnr2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6303fdae-3f2a-4149-80e2-5ac1b37f1b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_onetidHeadbnnr2</value>
      <webElementGuid>31ecab3a-f430-4add-b8a4-6fc2052c79bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-siteicon-img</value>
      <webElementGuid>329533a1-cf33-402a-a951-a2a29e3774d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onetidHeadbnnr0</value>
      <webElementGuid>b15ecc51-89f9-4a0b-99fe-d5cc51e35a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/SiteAssets/bi-b.png</value>
      <webElementGuid>7e6b5957-3ab4-4fcb-9380-13358fb3c370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Kurs Transaksi BI</value>
      <webElementGuid>5ed78fe4-0d59-4a2f-a93f-d466df9a34fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_onetidHeadbnnr2&quot;)</value>
      <webElementGuid>27804d67-3aec-4675-9d59-009a157f8388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_onetidHeadbnnr2']</value>
      <webElementGuid>5fcb879f-f2d7-4321-900b-89b88d3fd603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_onetidProjectPropertyTitleGraphic']/img</value>
      <webElementGuid>ffdfc3e4-e48d-4aff-a454-b433995d41ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Kurs Transaksi BI']</value>
      <webElementGuid>da1f9806-3eba-479d-bf46-1583460c57a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/a/img</value>
      <webElementGuid>6a5385d7-a6ec-4fff-9b26-bb612353bb53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ctl00_onetidHeadbnnr2' and @name = 'onetidHeadbnnr0' and @src = '/SiteAssets/bi-b.png' and @alt = 'Kurs Transaksi BI']</value>
      <webElementGuid>190054a0-cc65-43dc-b4ce-db72adea548d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
