<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_JAKARTA, KOMPAS.com_card-img-top</name>
   <tag></tag>
   <elementGuidId>163aefe3-6a74-49d9-929a-22060e73e760</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div[2]/div/div[2]/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d2644af-a1e1-45e4-b269-5fe60f0b29fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>8e9bb445-08b0-49c3-b3de-93de8e4264d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://10.201.79.218:1337/uploads/berita_e9373a040e.jpg</value>
      <webElementGuid>3534dd2e-6e61-419c-ad1e-41965bc82a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Card</value>
      <webElementGuid>ca923c23-00ce-4d2c-a95c-3971a371e868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid news px-3&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-md-7 col-lg-3 mb-3&quot;]/a[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-img-wrap&quot;]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>d305c30c-dcf7-4887-876a-d9047c0955b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div/div[2]/a/div/div/img</value>
      <webElementGuid>62458c45-4987-4ba9-aa93-c40fa8217638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Card'])[2]</value>
      <webElementGuid>ee0efae7-390c-4429-aa02-fd9fa9e5e615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/img</value>
      <webElementGuid>ecc6de8c-bff1-4adc-bae5-7280c507900a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://10.201.79.218:1337/uploads/berita_e9373a040e.jpg' and @alt = 'Card']</value>
      <webElementGuid>d015127e-4b97-4611-b22e-f19526c2248f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
