<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Profil_brand</name>
   <tag></tag>
   <elementGuidId>52501335-247b-460a-abe2-e5420fb396d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>654e2c0f-96b2-4c1e-b747-030d8e38d6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.style.display='none'</value>
      <webElementGuid>614d87d2-c736-4b60-a22f-069ec258e357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>1ea2fbda-6ede-4f38-bc4a-d484cf19d094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand</value>
      <webElementGuid>e846cdb6-5cd7-44cd-b8a4-4be39643b6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://media.kemenkeu.go.id/getmedia/dce5d80f-c267-48af-9181-b5db5f3910e6/logo-atas.png?width=1920&amp;height=483&amp;ext=.png</value>
      <webElementGuid>a746e1b6-13f1-4c4c-aad0-440aaafa957d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/kem-main-layout[1]/div[@class=&quot;kem-layout&quot;]/kem-o-navbar[1]/div[@class=&quot;kem-o-navbar&quot;]/kem-o-navbar-desktop[@class=&quot;tw-hidden lg:tw-block&quot;]/div[@class=&quot;kem-o-navbar-desktop tw-fixed tw-w-full tw-z-10&quot;]/div[@class=&quot;container-xl&quot;]/div[@class=&quot;tw-flex&quot;]/div[@class=&quot;kem-o-navbar-desktop__logo&quot;]/a[1]/img[@class=&quot;brand&quot;]</value>
      <webElementGuid>80b95000-ab69-4ad5-a3d5-ecf31504d640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>19fd06dd-4238-43c7-90d2-809d50b38212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>66e42d55-7388-403b-ba79-c9f4f8a25c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'logo' and @src = 'http://media.kemenkeu.go.id/getmedia/dce5d80f-c267-48af-9181-b5db5f3910e6/logo-atas.png?width=1920&amp;height=483&amp;ext=.png']</value>
      <webElementGuid>a28862cf-1cd1-45fd-b353-aeba41cdeca6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
