<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BERITA</name>
   <tag></tag>
   <elementGuidId>9b730299-2dc1-4454-8bca-1ba107fc05a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-5.d-flex.flex-column.justify-content-end.align-items-start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4473fddf-d55a-47c7-9950-fc25cb61ebd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-5 d-flex flex-column justify-content-end align-items-start</value>
      <webElementGuid>9d1f74c9-f739-46fa-bfa0-e10652d3f24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BERITA</value>
      <webElementGuid>61768c3b-834d-438e-a0a0-57193dd00683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid news px-3&quot;]/div[@class=&quot;row h-25 mb-4&quot;]/div[@class=&quot;col-5 d-flex flex-column justify-content-end align-items-start&quot;]</value>
      <webElementGuid>cbb01d33-4578-44b2-a94c-8cdba59d3481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div</value>
      <webElementGuid>2a093241-87d5-4cd3-bf5c-58cb426faab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/following::div[4]</value>
      <webElementGuid>3ff68130-9104-4d30-98d0-6cdb59791f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/following::div[4]</value>
      <webElementGuid>1e45df84-e343-4e82-a5b6-ca66e8d8cf4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berita 16'])[3]/preceding::div[6]</value>
      <webElementGuid>a360993a-4be3-460b-ba4d-49094aae8e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>e4d12309-dcda-42f6-91ec-95f6cdf7cb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'BERITA' or . = 'BERITA')]</value>
      <webElementGuid>6e5aed49-9919-4b9d-906e-4857fee3da0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
