<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Galeri</name>
   <tag></tag>
   <elementGuidId>3f19175a-7ff1-4c9e-be52-07b3106add95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.dropdown-item.d-flex.align-items-center.dropdown-item.link-style</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div[2]/div[3]/div/li/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57bb7348-a106-45bb-bd9f-4f17d9be433f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item d-flex align-items-center dropdown-item link-style</value>
      <webElementGuid>021e0167-bae2-4ece-8718-ecc087459593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Galeri »</value>
      <webElementGuid>eebfbcb9-764f-4e7e-9218-f1ab3339ea85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky-top&quot;]/nav[@class=&quot;navbar d-flex justify-content-between py-3&quot;]/div[@class=&quot;nav-link-container&quot;]/div[@class=&quot;link-style nav-item show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/li[1]/button[@class=&quot;dropdown-item d-flex align-items-center dropdown-item link-style&quot;]</value>
      <webElementGuid>ca2fbddb-56d4-48c5-bf9f-f532fea8df7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div[2]/div[3]/div/li/button</value>
      <webElementGuid>0d7bd0c1-4796-429f-b62b-1a49b77e2e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peraturan'])[1]/following::button[1]</value>
      <webElementGuid>201548bb-6ce2-4ae2-94f9-5a4e3ca6a1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karir'])[1]/following::button[1]</value>
      <webElementGuid>d2d4c6c8-ee1a-46c8-9d0b-84e2ffcbc55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foto'])[1]/preceding::button[1]</value>
      <webElementGuid>d8e06688-2fb5-48ec-a0d4-f4d17e4f1464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publikasi'])[1]/preceding::button[1]</value>
      <webElementGuid>b7a92df2-b302-4def-805e-a5b09f9cc648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Galeri']/parent::*</value>
      <webElementGuid>1a6481d4-f2c6-4823-929d-105719017445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button</value>
      <webElementGuid>481a866f-7cf1-49d6-b984-9ffa5f6a00fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Galeri »' or . = 'Galeri »')]</value>
      <webElementGuid>0fcfeecd-b1fa-4f29-b7df-6db67e6870d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
