<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_YOUTUBE_button-image_1_2</name>
   <tag></tag>
   <elementGuidId>e79d04e1-0aae-4de5-bc89-e06c98a324c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[5]/div/div[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a19d2635-2030-4ff5-9fa3-37ccf65a9db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/kurs.630e55ab4ace32257e45.jpeg</value>
      <webElementGuid>20060538-218f-4926-bdbf-62a47b0427be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>gm 2</value>
      <webElementGuid>431f2281-ca2e-40cf-ad7b-5a24636921f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-image</value>
      <webElementGuid>62c289fd-610a-49b7-b78f-f5364cecfe0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center content-square-home my-5&quot;]/div[@class=&quot;d-flex flex-wrap justify-content-center&quot;]/div[@class=&quot;col-lg-2 col-md-3 col-sm-4 col-6&quot;]/a[@class=&quot;btn btn-primary btn-sm square-button&quot;]/img[@class=&quot;button-image&quot;]</value>
      <webElementGuid>cf9f49b9-4f20-4dca-b2c9-a087573da6a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[5]/div/div[3]/a/img</value>
      <webElementGuid>9676ee08-32cc-4dcc-8ea3-40bd3652c079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='gm 2'])[2]</value>
      <webElementGuid>0af7364a-3f07-4ff7-8512-024316df0a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/img</value>
      <webElementGuid>6ffb7035-2071-4d15-813e-fbe7a79ab090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/kurs.630e55ab4ace32257e45.jpeg' and @alt = 'gm 2']</value>
      <webElementGuid>476a53e8-3fcf-4893-a34e-12eb2f184200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
