<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_YOUTUBE_button-image_1</name>
   <tag></tag>
   <elementGuidId>102b2295-53cc-43e8-9ae5-3a754b2c0077</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[5]/div/div[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>18fda99b-8145-4df3-8bf6-b9ce17a474e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/WB.98eed6248d06db212469.png</value>
      <webElementGuid>cb4c33d6-c81e-488b-a142-d6468fded7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>gm 2</value>
      <webElementGuid>b55df495-8f35-454f-ad6f-cd81ca6f63b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-image</value>
      <webElementGuid>402e6ab9-7483-4db7-b01d-b03500e31fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center content-square-home my-5&quot;]/div[@class=&quot;d-flex flex-wrap justify-content-center&quot;]/div[@class=&quot;col-lg-2 col-md-3 col-sm-4 col-6&quot;]/a[@class=&quot;btn btn-primary btn-sm square-button&quot;]/img[@class=&quot;button-image&quot;]</value>
      <webElementGuid>e098b3bb-d67f-4059-9e6e-a7c88843f123</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[5]/div/div[2]/a/img</value>
      <webElementGuid>f4759e31-c809-44e2-b0b4-7f9ed01044e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='gm 2']</value>
      <webElementGuid>e003f86d-8b11-4a90-a19f-7c4043233de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/img</value>
      <webElementGuid>037cb27c-963d-481d-a659-ed8642a49e6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/WB.98eed6248d06db212469.png' and @alt = 'gm 2']</value>
      <webElementGuid>e22936e7-2088-4c4c-9315-84794984c6d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
