<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1 (1)</name>
   <tag></tag>
   <elementGuidId>1566d544-8c00-49c5-8eaa-1df75331ce59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.carousel-control-next > span.carousel-arrow.carousel-arrow-home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5997328b-a2a9-4885-b9fb-da8b278b4c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-arrow carousel-arrow-home</value>
      <webElementGuid>2ab7ecb8-9190-4d6c-8992-65f76a145972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>›</value>
      <webElementGuid>aef989ac-5b92-449c-b3aa-69ea68940abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;content-carousel-home&quot;]/div[@class=&quot;carousel-container-home carousel slide&quot;]/a[@class=&quot;carousel-control-next&quot;]/span[@class=&quot;carousel-arrow carousel-arrow-home&quot;]</value>
      <webElementGuid>2dca0f11-76d8-4ae2-9100-42770682929b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/a[2]/span</value>
      <webElementGuid>b59622f4-b694-4490-b6cb-e1514a6fa1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::span[1]</value>
      <webElementGuid>3b6e5792-8369-481d-adfe-ff0e59d9eee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/following::span[2]</value>
      <webElementGuid>23a31fe4-7463-4145-8c74-b58a3fb2bf42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::span[1]</value>
      <webElementGuid>a4d9db87-68e8-4e60-993d-440d92bb9046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latest News'])[1]/preceding::span[2]</value>
      <webElementGuid>53c1f424-d4b1-4e7c-80ae-14bb06d3933e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='›']/parent::*</value>
      <webElementGuid>c14441c7-e406-4d78-8ece-7aea1aa9fa14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>945bfa33-23e5-467e-b5ca-74e976e928bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '›' or . = '›')]</value>
      <webElementGuid>390b0fac-2d64-456b-9bd2-f4637c73f4d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
