<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Pembukaan Undang-Undang Dasar 1945 mengam_47e4f7</name>
   <tag></tag>
   <elementGuidId>82efa43c-81fa-4136-8459-d20ddabd3d5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>13c44cfd-f132-49a7-80a0-4e16354eb660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pembukaan Undang-Undang Dasar 1945 mengamanatkan bahwa Negara Kesatuan Republik Indonesia memiliki tujuan untuk memajukan kesejahteraan umum, mencerdaskan kehidupan bangsa, dan ikut melaksanakan ketertiban dunia. Amanat untuk ikut melaksanakan ketertiban dunia dimaksud diimplementasikan melalui keterlibatan aktif Indonesia dalam mendukung pembangunan dunia, terutama untuk mengatasi kesenjangan sosial dan mengurangi kemiskinan.</value>
      <webElementGuid>90b5bd9a-a3c7-4481-a937-1d7e14598d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[2]/div[@class=&quot;px-5&quot;]/div[@class=&quot;mt-4&quot;]/div[@class=&quot;rich-text-container&quot;]/p[1]</value>
      <webElementGuid>47174d8b-a9c2-4e65-a6e5-9e5fb5254d0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div/p</value>
      <webElementGuid>e05427b8-8616-4771-af3e-e5d99bb9192a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sejarah'])[3]/following::p[1]</value>
      <webElementGuid>f9dd6c1b-48f2-4482-a7c2-e008798a32d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sejarah'])[2]/following::p[1]</value>
      <webElementGuid>c8978ba6-a0d2-4a7c-9aef-ca57c462bec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/preceding::p[2]</value>
      <webElementGuid>b4ec95d3-02fd-4597-8655-d597e567e921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mengamanatkan bahwa Negara Kesatuan Republik Indonesia memiliki tujuan untuk memajukan kesejahteraan umum, mencerdaskan kehidupan bangsa, dan ikut melaksanakan ketertiban dunia. Amanat untuk ikut melaksanakan ketertiban dunia dimaksud diimplementasikan melalui keterlibatan aktif Indonesia dalam mendukung pembangunan dunia, terutama untuk mengatasi kesenjangan sosial dan mengurangi kemiskinan.']/parent::*</value>
      <webElementGuid>24d15f57-94c7-4776-b5e3-c9ca17194260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>643b0293-396b-48f7-9730-4e3594712c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Pembukaan Undang-Undang Dasar 1945 mengamanatkan bahwa Negara Kesatuan Republik Indonesia memiliki tujuan untuk memajukan kesejahteraan umum, mencerdaskan kehidupan bangsa, dan ikut melaksanakan ketertiban dunia. Amanat untuk ikut melaksanakan ketertiban dunia dimaksud diimplementasikan melalui keterlibatan aktif Indonesia dalam mendukung pembangunan dunia, terutama untuk mengatasi kesenjangan sosial dan mengurangi kemiskinan.' or . = 'Pembukaan Undang-Undang Dasar 1945 mengamanatkan bahwa Negara Kesatuan Republik Indonesia memiliki tujuan untuk memajukan kesejahteraan umum, mencerdaskan kehidupan bangsa, dan ikut melaksanakan ketertiban dunia. Amanat untuk ikut melaksanakan ketertiban dunia dimaksud diimplementasikan melalui keterlibatan aktif Indonesia dalam mendukung pembangunan dunia, terutama untuk mengatasi kesenjangan sosial dan mengurangi kemiskinan.')]</value>
      <webElementGuid>4b2ce695-d344-4d53-84c9-ac2bf6c96ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
