<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Laporan Keuangan</name>
   <tag></tag>
   <elementGuidId>4c30816d-e775-4ef3-9aca-76cab4d545a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.d-flex.align-items-center.dropdown-item.link-style.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div[2]/div[3]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb4c3239-4b2a-4a18-85ee-010f0695de8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center dropdown-item link-style  dropdown-item</value>
      <webElementGuid>5d895c16-39ba-4fc0-9876-262d0f86fc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/informasi/laporanKeuangan</value>
      <webElementGuid>e1086c4e-d827-4b9b-9f18-8fb9bc481cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Laporan Keuangan</value>
      <webElementGuid>ce007811-f267-4919-ae00-b887cc3d3a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky-top&quot;]/nav[@class=&quot;navbar d-flex justify-content-between py-3&quot;]/div[@class=&quot;nav-link-container&quot;]/div[@class=&quot;link-style nav-item show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;d-flex align-items-center dropdown-item link-style  dropdown-item&quot;]</value>
      <webElementGuid>da60d3a4-c5ed-4823-b1d2-089a93fe1e0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div[2]/div[3]/div/a</value>
      <webElementGuid>b587a0ea-c55a-4203-8112-8c81d9576bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Laporan Keuangan')]</value>
      <webElementGuid>46fa2a31-cc91-4d62-9226-ed2d44efe658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berita'])[1]/following::a[2]</value>
      <webElementGuid>93978200-e48a-4c6e-a0af-96df34cc55e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::a[5]</value>
      <webElementGuid>97d376c9-4041-440c-9245-b816c6964634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pengadaan'])[1]/preceding::a[1]</value>
      <webElementGuid>07a985bd-6752-448b-b364-485f6e68a64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karir'])[1]/preceding::a[2]</value>
      <webElementGuid>a9eed346-1630-428f-8177-e75dfb426f45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Laporan Keuangan']/parent::*</value>
      <webElementGuid>b9fce9fd-4307-4cd3-8329-7b23d5da0bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/informasi/laporanKeuangan')]</value>
      <webElementGuid>1198243a-95b7-4e24-856e-8bdc67078f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a</value>
      <webElementGuid>d04edc59-ac07-42a3-9450-a8cdb01c218c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/informasi/laporanKeuangan' and (text() = 'Laporan Keuangan' or . = 'Laporan Keuangan')]</value>
      <webElementGuid>a058b5ef-5a0d-42c1-a5a8-5d926d43772d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
