<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LDKPI Meraih Opini Wajar Tanpa Pengecua_e17e47</name>
   <tag></tag>
   <elementGuidId>67c19c2e-0bfe-4afd-951f-172ca318c50f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[4]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.marquee-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>78440943-eead-4e2d-b06b-fba33b2d8d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>marquee-container</value>
      <webElementGuid>5897d624-a3f1-4d9d-8439-7e40f39ba7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LDKPI Meraih Opini Wajar Tanpa PengecualianLDKPI Menentang Keras Segala Bentuk Pemberian Berupa Uang, Barang dan Fasilitas Dalam Setiap Layanan KamiYOUTUBE</value>
      <webElementGuid>19723db5-da94-4e97-ae23-6645bed01fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;container-hibah mt-3&quot;]/div[@class=&quot;marquee-container&quot;]</value>
      <webElementGuid>65d2563b-671a-4e48-a6cc-6d0a4adc317e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[4]/div[2]</value>
      <webElementGuid>95cebd34-14eb-4124-91f0-144807a1607a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distribution of Realized Grants'])[1]/following::div[2]</value>
      <webElementGuid>da63b15e-1b6e-47c9-aa1b-290c626f0532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia AID'])[1]/following::div[6]</value>
      <webElementGuid>da01f46e-9649-40c2-b03e-fad0e04c34cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]</value>
      <webElementGuid>f29b4576-98b1-4176-9c61-1cf7c285c439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LDKPI Meraih Opini Wajar Tanpa PengecualianLDKPI Menentang Keras Segala Bentuk Pemberian Berupa Uang, Barang dan Fasilitas Dalam Setiap Layanan KamiYOUTUBE' or . = 'LDKPI Meraih Opini Wajar Tanpa PengecualianLDKPI Menentang Keras Segala Bentuk Pemberian Berupa Uang, Barang dan Fasilitas Dalam Setiap Layanan KamiYOUTUBE')]</value>
      <webElementGuid>678dcc5c-0d1d-40aa-8122-a742dbc205d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
