<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Organisasi_mt-5</name>
   <tag></tag>
   <elementGuidId>00a6c91b-8a42-4263-bf2f-6509b38174fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.mt-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4b38c80a-87f5-4d85-8dbc-2947d6d64519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gambar Organisasi</value>
      <webElementGuid>c68d3497-b78f-4152-9209-eefe1ed07f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-5</value>
      <webElementGuid>b5be96de-61cc-4f3e-906f-61d3bee25fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://10.201.79.218:1337/uploads/Organ_chartt_ID_49e97fcc62.png</value>
      <webElementGuid>43ae38b3-3ced-44d6-b54d-fd6b6653c410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[2]/div[@class=&quot;px-3&quot;]/div[1]/img[@class=&quot;mt-5&quot;]</value>
      <webElementGuid>6e5d632c-c4b2-4e6f-aa4f-599f3615d46e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/img</value>
      <webElementGuid>f9627590-2f7b-46f5-a2c2-fa616598908c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gambar Organisasi']</value>
      <webElementGuid>e8d622c5-1266-4469-8dba-d156e22aa9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>2388f3af-c24d-49df-b335-b61fd8cf4a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Gambar Organisasi' and @src = 'http://10.201.79.218:1337/uploads/Organ_chartt_ID_49e97fcc62.png']</value>
      <webElementGuid>d6d3e628-9c70-40f2-b3eb-38ad5c724d0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
