<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mabar anjay- 19 Juli 2023Indonesia dike_96a059</name>
   <tag></tag>
   <elementGuidId>b08e6a26-7314-416c-b98f-6f6c288d97cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.active.carousel-item > a > div.photo-page > div.image-container-foto > div.overlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div[2]/div/div[2]/div[2]/a/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bceeb3c2-5f71-44f0-b132-85196e0e47f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay</value>
      <webElementGuid>6020648d-a412-4c9b-a908-2e386819d789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mabar anjay- 19 Juli 2023Indonesia dikenal sebagai salah satu negara maritim terbesar di dunia yang ditunjang dengan garis pantai yang sedemikian panjangnya. Dengan...</value>
      <webElementGuid>18ac2085-a452-4a10-bd32-a12657f3684c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;home-foto&quot;]/div[@class=&quot;content-carousel-foto&quot;]/div[@class=&quot;carousel-container-foto carousel slide&quot;]/div[@class=&quot;carousel-inner&quot;]/div[@class=&quot;active carousel-item&quot;]/a[1]/div[@class=&quot;photo-page&quot;]/div[@class=&quot;image-container-foto&quot;]/div[@class=&quot;overlay&quot;]</value>
      <webElementGuid>4dbac4ab-9f1d-45a8-91b3-f28edfb2b31e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div[2]/div/div[2]/div[2]/a/div/div/div[2]</value>
      <webElementGuid>8f6d809a-4cb5-4c3f-b0d6-165f7c1e85cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia dikenal sebagai salah satu negara'])[1]/following::div[5]</value>
      <webElementGuid>14465e46-6c54-4b3d-a1b5-4208723337d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div/div[2]</value>
      <webElementGuid>4319cee4-5c11-4ab1-b2bd-8919b89f892c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Mabar anjay- 19 Juli 2023Indonesia dikenal sebagai salah satu negara maritim terbesar di dunia yang ditunjang dengan garis pantai yang sedemikian panjangnya. Dengan...' or . = 'Mabar anjay- 19 Juli 2023Indonesia dikenal sebagai salah satu negara maritim terbesar di dunia yang ditunjang dengan garis pantai yang sedemikian panjangnya. Dengan...')]</value>
      <webElementGuid>7626b575-d952-447d-8a1c-9e642fa74604</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
