<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Previous_carousel-control-next-icon</name>
   <tag></tag>
   <elementGuidId>48755438-a508-4247-bd4f-a465cf7a354d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.carousel-control-next-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div[2]/div/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3df37ad4-c283-4357-8fd3-eebe9921200f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>abba4df2-d8d3-4e92-82f4-74392372154f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>carousel-control-next-icon</value>
      <webElementGuid>bf7870c8-4fff-447c-9bc4-2559bf190e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;home-foto&quot;]/div[@class=&quot;content-carousel-foto&quot;]/div[@class=&quot;carousel-container-foto carousel slide&quot;]/a[@class=&quot;carousel-control-next&quot;]/span[@class=&quot;carousel-control-next-icon&quot;]</value>
      <webElementGuid>00c05b16-5aad-423f-b847-b0bcc987bbc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div[2]/div/a[2]/span</value>
      <webElementGuid>a2fb53f4-8980-44c7-a13e-22d50642b11b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>7d1357a4-20f4-4dc2-9464-6c8b9206c5c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
