<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Peta Situs_onetidHeadbnnr0</name>
   <tag></tag>
   <elementGuidId>8c2fa1cb-461f-4691-92e7-28a64730458a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_onetidHeadbnnr2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='ctl00_onetidHeadbnnr2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>08ba21aa-32db-43b1-a555-f5893d61ccfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_onetidHeadbnnr2</value>
      <webElementGuid>c5739181-5301-48bc-8903-f55e079c3e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-siteicon-img</value>
      <webElementGuid>954bdbb0-7218-4762-a936-dc0eb86d398e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>onetidHeadbnnr0</value>
      <webElementGuid>e53dc9cf-4358-4ab5-93c8-3e3d3b30c994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/SiteAssets/bi-b.png</value>
      <webElementGuid>53eda5a7-afed-4a96-b8b4-68a0992f7fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Kurs Transaksi BI</value>
      <webElementGuid>6ef315ba-018e-40db-b9f9-8ba9c2bb4a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_onetidHeadbnnr2&quot;)</value>
      <webElementGuid>e9343aaa-0f45-4247-9d4c-bc6ca50a564b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='ctl00_onetidHeadbnnr2']</value>
      <webElementGuid>624986ed-d63a-4b75-8c05-761de602a277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ctl00_onetidProjectPropertyTitleGraphic']/img</value>
      <webElementGuid>e0ad1f94-3c0b-4077-87ad-8b1a2637ed33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Kurs Transaksi BI']</value>
      <webElementGuid>e927b41a-4417-4f6f-9f17-9353c9b23433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div/a/img</value>
      <webElementGuid>8f9dc20f-c849-4470-b215-ded296829e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'ctl00_onetidHeadbnnr2' and @name = 'onetidHeadbnnr0' and @src = '/SiteAssets/bi-b.png' and @alt = 'Kurs Transaksi BI']</value>
      <webElementGuid>03c27d91-871f-4aa7-88cf-aee713a9aadd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
