<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_YOUTUBE_button-image</name>
   <tag></tag>
   <elementGuidId>411bcf25-2b54-45d2-97f7-038f21b17893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.button-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[5]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e215a147-b00e-4860-94d3-5122926cf65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/kemenkeu.4d938ab49a85ba2081fd.png</value>
      <webElementGuid>84783f85-119c-41b8-952a-31ab53baaabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>gm 1</value>
      <webElementGuid>d821c0b5-8a61-4a7b-998f-1fc51237a402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-image</value>
      <webElementGuid>dc1fc8e8-dc6b-47ab-9f6b-a999794eb461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center content-square-home my-5&quot;]/div[@class=&quot;d-flex flex-wrap justify-content-center&quot;]/div[@class=&quot;col-lg-2 col-md-3 col-sm-4 col-6&quot;]/a[@class=&quot;btn btn-primary btn-sm square-button&quot;]/img[@class=&quot;button-image&quot;]</value>
      <webElementGuid>08a962c0-a659-400d-920a-1372c7b7dfdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[5]/div/div/a/img</value>
      <webElementGuid>5def9c1a-81ca-4b0f-9304-06085029d3e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='gm 1']</value>
      <webElementGuid>05c2e89d-36f7-44b7-afc9-9b54e0fcb13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/img</value>
      <webElementGuid>1cef2c80-e776-4c75-a9d5-c5c14271576b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/kemenkeu.4d938ab49a85ba2081fd.png' and @alt = 'gm 1']</value>
      <webElementGuid>a696dca9-3fa7-4a1d-ab7f-90f096b5257a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
