<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>450605f8-9df6-4641-9b63-ce1d474b84c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Gambar Tugas dan Fungsi LDKPI&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7d9587ae-f1fe-4c1c-99ef-3346df0823dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gambar Tugas dan Fungsi LDKPI</value>
      <webElementGuid>eb7da7ea-3488-4108-b107-80018cea6d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://10.201.79.218:1337/uploads/Tugas_Fungsi_Indo_ver2_ff37a09bf7.png</value>
      <webElementGuid>ba86b3e0-6c17-4524-aeac-a40c3f7b68a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[2]/div[@class=&quot;px-3 pt-2&quot;]/div[1]/img[1]</value>
      <webElementGuid>2cda8a54-a71f-42f5-822b-9b551126d4cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/img</value>
      <webElementGuid>e286d2a3-b2dd-4ed7-a114-abcf114a9b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gambar Tugas dan Fungsi LDKPI']</value>
      <webElementGuid>65cc1e13-426b-444e-ac0c-015a4115263e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>496097ef-ccc8-4f54-bd80-700056613ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Gambar Tugas dan Fungsi LDKPI' and @src = 'http://10.201.79.218:1337/uploads/Tugas_Fungsi_Indo_ver2_ff37a09bf7.png']</value>
      <webElementGuid>5f18a2fa-9b86-4bf0-b05c-d34af3f49a92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
