<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_25 Juni 2023Jonski HomskiIndonesia dike_6859db</name>
   <tag></tag>
   <elementGuidId>84e8e618-90e0-4b25-95b7-a80975ea3f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card.card-foto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div[4]/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>458054f8-8022-43f9-abec-e8bd425ceb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card card-foto</value>
      <webElementGuid>6399ffdf-b21a-4607-805f-89f9ac32d880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25 Juni 2023Jonski HomskiIndonesia dikenal sebagai salah satu negara maritim terbesar di dunia yang ditunjang dengan garis pantai yang sedemikian panjangnya. Dengan...</value>
      <webElementGuid>fac09e56-7d35-4442-89e8-4e486f4eee53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;home-foto&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-sm-6 mb-3&quot;]/a[1]/div[@class=&quot;card card-foto&quot;]</value>
      <webElementGuid>4cc6b748-4fd8-4b04-a9ad-78dd045cd3b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div[4]/div/a/div</value>
      <webElementGuid>460e7860-4a68-4d4b-b074-4595429bee07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[4]</value>
      <webElementGuid>a6f91f36-ad88-498f-a624-43c13fcaed1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::div[4]</value>
      <webElementGuid>74563d80-4402-453b-8a66-7d43f1f07a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/div</value>
      <webElementGuid>953c4cb8-3570-4464-bf2f-e5e15c318422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '25 Juni 2023Jonski HomskiIndonesia dikenal sebagai salah satu negara maritim terbesar di dunia yang ditunjang dengan garis pantai yang sedemikian panjangnya. Dengan...' or . = '25 Juni 2023Jonski HomskiIndonesia dikenal sebagai salah satu negara maritim terbesar di dunia yang ditunjang dengan garis pantai yang sedemikian panjangnya. Dengan...')]</value>
      <webElementGuid>ec9a5534-ee64-4396-88c2-3453e7b76c12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
