<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Indonesia dikenal sebagai salah satu ne_e8e97d</name>
   <tag></tag>
   <elementGuidId>e42a0817-3b77-40ec-beaa-7eced1d03d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia dikenal sebagai salah satu negara'])[1]/following::*[name()='svg'][4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>66a4e164-c53a-478a-9bda-cc97d245e4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d37bf9ec-b366-4b92-a705-72b3bf133759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>532601ab-6e5d-4eb8-85e3-2ee8fd3e9ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fab</value>
      <webElementGuid>e7d73988-3ead-4425-b06d-874654e3c155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>facebook</value>
      <webElementGuid>bc7ff1d9-1c08-49c9-b41a-18ed997c9328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-facebook </value>
      <webElementGuid>3fab0933-60c5-4348-8361-791e20895108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>37e65b7c-76f6-46d4-8526-9bffdee6f9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>722887f1-d2dc-47c0-9faf-bdfb21568ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 512 512</value>
      <webElementGuid>02a182c3-88ee-4d50-a3d7-88f0699bf42e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;outside&quot;]/div[@class=&quot;row align-items-center justify-content-center&quot;]/div[@class=&quot;col-4 col-sm-3&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-4 col-sm-3 text-center&quot;]/button[@class=&quot;circle-button-showfoto2&quot;]/a[1]/svg[@class=&quot;svg-inline--fa fa-facebook&quot;]</value>
      <webElementGuid>096bf6c0-3a9c-468a-97cb-0f67e263b983</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia dikenal sebagai salah satu negara'])[1]/following::*[name()='svg'][4]</value>
      <webElementGuid>549b936b-c6a6-411c-a187-d03487458365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>54b57440-0410-49da-9526-54b198586ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prasyarat'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>56a9f78d-f32d-4bc4-b574-b3fb02871f2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
