<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Proses Bisnis Pemberian Hibah</name>
   <tag></tag>
   <elementGuidId>a60b763c-de8f-4955-8be8-05d0ed00bf26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.d-flex.align-items-center.dropdown-item.link-style.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/nav/div[2]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4e48bc64-8c9a-4b77-9555-8320f76a7997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center dropdown-item link-style  dropdown-item</value>
      <webElementGuid>127beff0-baa7-4915-9a8d-48770c917460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/hibah/prosesBisnis</value>
      <webElementGuid>0f2b3550-f777-470a-b7b9-613c6cc03c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proses Bisnis Pemberian Hibah</value>
      <webElementGuid>7e572f32-b8a2-4b12-845a-9eb13daf6f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky-top&quot;]/nav[@class=&quot;navbar d-flex justify-content-between py-3&quot;]/div[@class=&quot;nav-link-container&quot;]/div[@class=&quot;link-style nav-item show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;d-flex align-items-center dropdown-item link-style  dropdown-item&quot;]</value>
      <webElementGuid>d99602cf-1cf0-469b-b4ce-4fad32d29e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/nav/div[2]/div[2]/div/a</value>
      <webElementGuid>7d2780c6-0b8b-4fff-8721-a896017dcb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Proses Bisnis Pemberian Hibah')]</value>
      <webElementGuid>80bfab6a-51aa-48d5-aa5a-5adc51383bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beranda'])[1]/following::a[3]</value>
      <webElementGuid>05063c36-a6a5-4d28-aba8-9c1f24c65c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::a[5]</value>
      <webElementGuid>75939930-4850-4a93-85ce-0c96ef866235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penerima Hibah'])[1]/preceding::a[1]</value>
      <webElementGuid>14836c3c-554d-4223-bcb2-2d4bc4d80e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berita'])[1]/preceding::a[2]</value>
      <webElementGuid>f4ece9aa-4e08-458a-867b-66df28c7022d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proses Bisnis Pemberian Hibah']/parent::*</value>
      <webElementGuid>e37b9b98-9911-4d53-905d-73ea6dd103ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/hibah/prosesBisnis')]</value>
      <webElementGuid>b45d54dc-9c25-41a6-86a4-54b454f69d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[2]/div[2]/div/a</value>
      <webElementGuid>9b24b72d-6df2-4525-9dae-fb69583389f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/hibah/prosesBisnis' and (text() = 'Proses Bisnis Pemberian Hibah' or . = 'Proses Bisnis Pemberian Hibah')]</value>
      <webElementGuid>eb0dd13f-6da0-4ff7-956d-279e23c645b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
