<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LDKPI Meraih Opini Wajar Tanpa Pengecualian</name>
   <tag></tag>
   <elementGuidId>00bae464-d72b-406b-82c6-7aa8146c2dd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.marquee-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[4]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>56dd7f41-24cc-44ee-98bc-b81828e54d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>marquee-link</value>
      <webElementGuid>be05d469-d1df-4120-880c-4a6f9cedc629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ldkpi.kemenkeu.go.id/post/ldkpi-meraih-opini-wajar-tanpa-pengecualian</value>
      <webElementGuid>c756e6a6-cc1b-4695-bc0a-7be8afc18c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>6403d15f-059c-4fdc-aa32-a2f3b131807c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LDKPI Meraih Opini Wajar Tanpa Pengecualian</value>
      <webElementGuid>50709885-43e6-49fe-95d3-7b2c4c6ca4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;container-hibah mt-3&quot;]/div[@class=&quot;marquee-container&quot;]/div[@class=&quot;marquee-content&quot;]/a[@class=&quot;marquee-link&quot;]</value>
      <webElementGuid>7a3c51cb-b20b-4398-9a97-7862df72a0b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[4]/div[2]/div/a</value>
      <webElementGuid>5ccd0164-c8c0-4b91-a6b2-c57f447d7508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LDKPI Meraih Opini Wajar Tanpa Pengecualian')]</value>
      <webElementGuid>c917f5ed-7c37-4273-86e4-c387885339f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Distribution of Realized Grants'])[1]/following::a[1]</value>
      <webElementGuid>15733ce9-968c-44bf-95d9-e3c910f26346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia AID'])[1]/following::a[1]</value>
      <webElementGuid>a733043b-77c4-4408-aa97-d1863508dbab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUTUBE'])[1]/preceding::a[2]</value>
      <webElementGuid>29ecb0c3-0c00-4f6c-93c4-3818844c8c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direktorat Jenderal Perbendaharaan'])[1]/preceding::a[8]</value>
      <webElementGuid>af5d8028-f754-4f1e-a1e8-cc70b652eaf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LDKPI Meraih Opini Wajar Tanpa Pengecualian']/parent::*</value>
      <webElementGuid>887425a9-7104-4418-8c0b-961dc8219f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ldkpi.kemenkeu.go.id/post/ldkpi-meraih-opini-wajar-tanpa-pengecualian')]</value>
      <webElementGuid>73281ed5-b843-4ddd-be9a-71a5dd916f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/a</value>
      <webElementGuid>175df1ea-c158-4706-a6b6-7d2fb34b190f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ldkpi.kemenkeu.go.id/post/ldkpi-meraih-opini-wajar-tanpa-pengecualian' and (text() = 'LDKPI Meraih Opini Wajar Tanpa Pengecualian' or . = 'LDKPI Meraih Opini Wajar Tanpa Pengecualian')]</value>
      <webElementGuid>004c3fb8-ee43-4704-ac61-6f823abfe915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
