<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sekretariat Jenderal</name>
   <tag></tag>
   <elementGuidId>8075dc71-b219-44b2-937d-78210a612034</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.owl-item.cloned.active > a > div.square</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[6]/div/div/div[18]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dff5c809-8573-464d-9d56-829f25932fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>square</value>
      <webElementGuid>47ee31fc-fbcf-4c60-80e0-da30f94ef11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sekretariat Jenderal</value>
      <webElementGuid>fae90b24-bfb7-47cb-95f2-385d77643183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;owl-carousel owl-theme owl-loaded owl-drag&quot;]/div[@class=&quot;owl-stage-outer&quot;]/div[@class=&quot;owl-stage&quot;]/div[@class=&quot;owl-item cloned active&quot;]/a[1]/div[@class=&quot;square&quot;]</value>
      <webElementGuid>c36007bf-1aea-44e9-9b7c-d670d05640bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[6]/div/div/div[18]/a/div</value>
      <webElementGuid>a54e1250-2521-4415-ac6d-4cb24ec29be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Badan Pendidikan dan Pelatihan Keuanganl'])[2]/following::div[2]</value>
      <webElementGuid>f3dc992f-d2fd-4bdc-9c19-b4616e78a789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Badan Kebijakan Fiskal'])[2]/following::div[4]</value>
      <webElementGuid>7457351c-1d83-4ecc-9ac0-568edc9019bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inspektorat Jenderal'])[2]/preceding::div[1]</value>
      <webElementGuid>0a7eefcd-f2d5-4c42-89ac-421e509718a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/a/div</value>
      <webElementGuid>1563b135-aaea-4114-9970-8322054b92aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sekretariat Jenderal' or . = 'Sekretariat Jenderal')]</value>
      <webElementGuid>5591eb17-629c-4813-9873-34eb417f6b52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
