<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pengadaan Barang dan Jasa di lingkunga_171fcc</name>
   <tag></tag>
   <elementGuidId>469ced34-f1d7-4d00-888d-6e1f22b831b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.text-huge</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div/div/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>99ad1065-384a-4384-8d8d-9fcc5d73b0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-huge</value>
      <webElementGuid>c73f7ec2-b4de-4321-98cf-dd7238fd008c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengadaan Barang dan Jasa di lingkungan LDKPI mengacu pada Perdirut LDKPI No. 1 Tahun 2021 tentang Pedoman Pengadaan Barang dan Jasa pada BLU LDKPI.</value>
      <webElementGuid>c3d651cc-e487-4fa8-8e38-ae5691daa7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[2]/div[@class=&quot;px-5 pt-5&quot;]/div[1]/div[@class=&quot;rich-text-container&quot;]/p[1]/span[@class=&quot;text-huge&quot;]</value>
      <webElementGuid>3c4d9f5b-fca7-45eb-9d99-f7132a8b9727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div/p/span</value>
      <webElementGuid>e3543213-3912-498e-85f6-956622e8c72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pengadaan'])[3]/following::span[1]</value>
      <webElementGuid>7cb59cf5-8ef8-46f7-b365-ff4df571855f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi Pengadaan'])[2]/following::span[3]</value>
      <webElementGuid>c16fd5b9-fb17-4286-a44d-e67b4ad5a35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi Kami'])[1]/preceding::span[1]</value>
      <webElementGuid>6d16fb88-f083-411b-a790-d115145a4cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prasyarat'])[1]/preceding::span[2]</value>
      <webElementGuid>547de869-98ce-45f3-985e-396222d6399e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pengadaan Barang dan Jasa di lingkungan LDKPI mengacu pada Perdirut LDKPI No. 1 Tahun 2021 tentang Pedoman Pengadaan Barang dan Jasa pada BLU LDKPI.']/parent::*</value>
      <webElementGuid>d8d41133-020a-4f9a-ba0a-3acb973f9334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span</value>
      <webElementGuid>f7538e21-acc7-4c30-94ed-59838f157db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pengadaan Barang dan Jasa di lingkungan LDKPI mengacu pada Perdirut LDKPI No. 1 Tahun 2021 tentang Pedoman Pengadaan Barang dan Jasa pada BLU LDKPI.' or . = 'Pengadaan Barang dan Jasa di lingkungan LDKPI mengacu pada Perdirut LDKPI No. 1 Tahun 2021 tentang Pedoman Pengadaan Barang dan Jasa pada BLU LDKPI.')]</value>
      <webElementGuid>9731520d-1fc8-4abe-91f0-cd515e0d2c89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
