<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Publikasi_form-control search-bar</name>
   <tag></tag>
   <elementGuidId>ff4b3bfe-0d0a-46b6-ad5c-4180c60559ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.search-bar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aacfbec3-d78f-4287-8fcd-29c879aeae27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de5fe401-41b2-42df-9ce0-8501c5cc3c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan kata pencarian</value>
      <webElementGuid>556ec0fd-34c5-4a71-9894-b80e6d9cd2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control search-bar</value>
      <webElementGuid>81d1491c-5bad-4d0d-9f69-e262fc38827d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[@class=&quot;row h-25 mt-4 d-flex justify-content-end&quot;]/div[@class=&quot;col-4 d-flex flex-column justify-content-end align-items-end search-bar-container&quot;]/div[@class=&quot;input-group&quot;]/input[@class=&quot;form-control search-bar&quot;]</value>
      <webElementGuid>28b669fc-6d0d-4d05-a347-38fc8adb5d49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>d641ad52-3211-4c4b-96c8-8d72b1d60157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>855b02d4-3835-41c7-b062-f317dcaf840b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b9e3bcf3-462e-4ca0-9820-22b01759264c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Masukkan kata pencarian']</value>
      <webElementGuid>e977cc38-96cb-44c4-b3bc-87cffcff6cbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
