<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LDKPI Meraih Opini Wajar Tanpa Pengecualian</name>
   <tag></tag>
   <elementGuidId>0605878c-b703-45ed-a22b-309b486dcc1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.marquee-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[4]/div[2]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f95f3c3-6e5a-43b5-a845-315f83e5a158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>marquee-link</value>
      <webElementGuid>d5d85817-1ba2-41fa-9267-df490db5af3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://ldkpi.kemenkeu.go.id/post/ldkpi-meraih-opini-wajar-tanpa-pengecualian</value>
      <webElementGuid>01be1497-03ad-44c4-a87f-d4a2efe6fea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>fc1e6ffd-4126-4002-9ec0-bceb669458c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LDKPI Meraih Opini Wajar Tanpa Pengecualian</value>
      <webElementGuid>f09f1289-a531-40f3-8c14-0ebcb43f7923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;container-hibah mt-3&quot;]/div[@class=&quot;marquee-container&quot;]/div[@class=&quot;marquee-content&quot;]/a[@class=&quot;marquee-link&quot;]</value>
      <webElementGuid>9bdb5cbc-6647-4c19-8f31-27e999f2b860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[4]/div[2]/div/a</value>
      <webElementGuid>34ecfd94-d2a9-4e28-b147-7fa73efcff99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LDKPI Meraih Opini Wajar Tanpa Pengecualian')]</value>
      <webElementGuid>5c2e73eb-f9d6-46a7-89f6-c8d8bc8b2c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebaran Realisasi Hibah'])[1]/following::a[1]</value>
      <webElementGuid>1b7b9a7b-793a-4cf1-9897-293b819a43f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil LDKPI'])[1]/following::a[1]</value>
      <webElementGuid>3436199f-a6e2-4854-8f6f-dc514238251b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YOUTUBE'])[1]/preceding::a[2]</value>
      <webElementGuid>558472de-23ab-45ba-924d-965fd5afe673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direktorat Jenderal Perbendaharaan'])[1]/preceding::a[8]</value>
      <webElementGuid>4ddc9f51-642a-4ac0-9149-30949f84de66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LDKPI Meraih Opini Wajar Tanpa Pengecualian']/parent::*</value>
      <webElementGuid>e8ae7538-12e4-414c-bd72-f0a18569057f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://ldkpi.kemenkeu.go.id/post/ldkpi-meraih-opini-wajar-tanpa-pengecualian')]</value>
      <webElementGuid>492a9555-148b-4d48-a01f-27deab1b377d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/a</value>
      <webElementGuid>665099d5-3317-4853-a906-f3c4e6754ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://ldkpi.kemenkeu.go.id/post/ldkpi-meraih-opini-wajar-tanpa-pengecualian' and (text() = 'LDKPI Meraih Opini Wajar Tanpa Pengecualian' or . = 'LDKPI Meraih Opini Wajar Tanpa Pengecualian')]</value>
      <webElementGuid>ad83b9ae-9d86-4236-8e7f-239886754b73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
