<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_EN</name>
   <tag></tag>
   <elementGuidId>eb9091d2-5cd2-49b2-86a8-22a231905d03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn-language.btn.btn-primary.mr-2.btn-no-bg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a54b485f-964c-40f8-9be3-4730b069d67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-language btn btn-primary mr-2 btn-no-bg</value>
      <webElementGuid>56bcb207-567f-4952-a8b3-92cf45bd0e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EN</value>
      <webElementGuid>87ef003d-2a3f-4688-ae04-7bdd6caf7ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky-top&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row justify-content-end align-items-center py-2 px-3&quot;]/div[@class=&quot;col-lg-auto py-2 align-items-center&quot;]/div[@class=&quot;mr-2&quot;]/div[@class=&quot;language-switcher&quot;]/button[@class=&quot;btn-language btn btn-primary mr-2 btn-no-bg&quot;]</value>
      <webElementGuid>87f7db99-4de6-4ce7-9388-6fc5bd45d42c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div/div/button[2]</value>
      <webElementGuid>48babd4b-7aaa-4357-ae8a-1da9a239e847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::button[1]</value>
      <webElementGuid>513c651e-9198-4147-869f-65d6d211c259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lembaga Dana Kerja SamaPembangunan Internasional'])[1]/following::button[2]</value>
      <webElementGuid>ef590c28-a267-41ca-a05e-b21b587a693d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::button[1]</value>
      <webElementGuid>ad0d586d-874a-4b97-ae32-df58e835a452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EN']/parent::*</value>
      <webElementGuid>b3408d70-aaec-4b60-b31d-d478cb80bc68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>7beb8f2c-c4b2-445c-9b3e-b78d617b13f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'EN' or . = 'EN')]</value>
      <webElementGuid>f1c2c3b3-fb8d-41c6-812f-91a46fbbc58b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
