<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Kalkulator Kurs</name>
   <tag></tag>
   <elementGuidId>05a0145c-7b8c-4cb1-8b46-c6a4c21f7fbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content-wrapper']/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>078fdb2e-4834-44a9-9c08-821450fecb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kalkulator Kurs</value>
      <webElementGuid>172a1b59-5b9a-4cdb-bf92-90d5c374fc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content-wrapper&quot;)/h2[1]</value>
      <webElementGuid>a579bb8e-4f10-45e3-b77f-a1e3acf6e206</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content-wrapper']/h2</value>
      <webElementGuid>c7b5aaa9-f475-459e-89a9-a17ca1372259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start;Home;Statistik;Informasi Kurs;default.aspx;Bukan Sifibi;kalkulator-kurs.aspx;Kalkulator Kurs'])[1]/following::h2[1]</value>
      <webElementGuid>5a145a2d-eda1-4ca7-87bb-d2ca1dac6bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalkulator Kurs'])[3]/following::h2[1]</value>
      <webElementGuid>015b84ab-e579-41bf-b997-69188391d294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Transaksi'])[1]/preceding::h2[1]</value>
      <webElementGuid>93566cd3-d1e6-4908-b251-70a28897dd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nominal'])[1]/preceding::h2[1]</value>
      <webElementGuid>f0d64899-9a68-4bde-807a-3576bdef555b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>674e2336-0d00-42fd-8ed3-f04f11fe82a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Kalkulator Kurs' or . = 'Kalkulator Kurs')]</value>
      <webElementGuid>1500ad5f-2b20-471b-b9e0-4f309bc6fe19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
