<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_News 16Jakarta - July 13, 2023JAKARTA, _23054e</name>
   <tag></tag>
   <elementGuidId>a8351efa-137a-4d5e-a86a-ad21afef5f7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div[2]/div/a/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5bd0fdb5-8098-4fb4-bc4c-7abf48e089a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body</value>
      <webElementGuid>3db605f9-b9cd-4da6-aaec-39d8be4a53f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News 16Jakarta - July 13, 2023JAKARTA, KOMPAS.com – The case related to the leader of Al Zaytun Islamic Boarding School (Ponpes), Panji Gumilang, has entered...</value>
      <webElementGuid>69e2c9b9-148c-42d4-b748-761f869c796c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;container-fluid latest-news px-3&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-md-3 mb-4&quot;]/a[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]</value>
      <webElementGuid>0e791f87-07a2-49e3-ab10-5986c37693d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div[2]/div/a/div/div[2]</value>
      <webElementGuid>f03c24e6-0373-4759-a8c0-d4d998563d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latest News'])[1]/following::div[5]</value>
      <webElementGuid>b66ccc7e-097f-498a-a0ae-978040d66b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[10]</value>
      <webElementGuid>dc196127-c8c8-470c-94a3-525cbba4ebc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div[2]</value>
      <webElementGuid>4f7feb22-7d5a-493d-b463-28da9e69dc0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'News 16Jakarta - July 13, 2023JAKARTA, KOMPAS.com – The case related to the leader of Al Zaytun Islamic Boarding School (Ponpes), Panji Gumilang, has entered...' or . = 'News 16Jakarta - July 13, 2023JAKARTA, KOMPAS.com – The case related to the leader of Al Zaytun Islamic Boarding School (Ponpes), Panji Gumilang, has entered...')]</value>
      <webElementGuid>dd7611dd-7dd5-4d3d-b50b-1aba9b6183c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
