<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_I. Tantangan global</name>
   <tag></tag>
   <elementGuidId>d9645123-e4dc-48f8-a94f-b05ca0397cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ecef750-6567-4825-aa70-ae1e982d105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-description</value>
      <webElementGuid>2633d341-d049-44aa-8ef5-5817b8c1c173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>I.  Tantangan global, Hibah Internasional dan LDKPISejak tahun 2015 hingga tahun 2019, Indonesia mampu mencapai pertumbuhan ekonomi yang stabil sebesar 5 persen (BPS, 2020). Pertumbuhan ini berkontribusi pada penurunan kemiskinan menjadi 9.6 persen, pengangguran menjadi 5.3 persen dan ketimpangan (Gini) menjadi 0.38 (BPS, 2019).   Bahkan IMF (2019) sempat...</value>
      <webElementGuid>c229991a-31fe-47a6-be40-372da9241313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[3]/div[@class=&quot;card-publication&quot;]/a[@class=&quot;read-more-button&quot;]/div[@class=&quot;card-description&quot;]</value>
      <webElementGuid>45d6775b-390e-4f0a-8664-3687d1085ef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/a/div[2]</value>
      <webElementGuid>8819b62f-f14b-43b1-8446-3714b88ee432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publikasi Ketiga'])[1]/following::div[1]</value>
      <webElementGuid>f9170441-ed8e-422d-a692-f6fa9614f918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publikasi'])[3]/following::div[8]</value>
      <webElementGuid>0aefa31e-774c-4ad2-a7b2-34f7c295f9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>c36d7a4c-5fe7-428d-8cc1-320ebf939a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'I.  Tantangan global, Hibah Internasional dan LDKPISejak tahun 2015 hingga tahun 2019, Indonesia mampu mencapai pertumbuhan ekonomi yang stabil sebesar 5 persen (BPS, 2020). Pertumbuhan ini berkontribusi pada penurunan kemiskinan menjadi 9.6 persen, pengangguran menjadi 5.3 persen dan ketimpangan (Gini) menjadi 0.38 (BPS, 2019).   Bahkan IMF (2019) sempat...' or . = 'I.  Tantangan global, Hibah Internasional dan LDKPISejak tahun 2015 hingga tahun 2019, Indonesia mampu mencapai pertumbuhan ekonomi yang stabil sebesar 5 persen (BPS, 2020). Pertumbuhan ini berkontribusi pada penurunan kemiskinan menjadi 9.6 persen, pengangguran menjadi 5.3 persen dan ketimpangan (Gini) menjadi 0.38 (BPS, 2019).   Bahkan IMF (2019) sempat...')]</value>
      <webElementGuid>c50fb490-eb27-4fbc-a5a2-597a7d4f4cc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
