<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Publikasi Ketiga</name>
   <tag></tag>
   <elementGuidId>8cb349b3-3e62-4cff-820b-a2442478d322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.card-title-publication</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c40d7a7-e5d1-4d5a-b8ca-02df07f1c95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-title-publication</value>
      <webElementGuid>688944e0-06fd-4b75-b6b2-29d84cf6aced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Publikasi Ketiga</value>
      <webElementGuid>f471da5d-a3e6-4d13-bc70-00076d1a07aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[2]/div[3]/div[@class=&quot;card-publication&quot;]/a[@class=&quot;read-more-button&quot;]/div[@class=&quot;card-title-publication&quot;]</value>
      <webElementGuid>d12cf452-0996-488e-91a9-002d34037f8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div/a/div</value>
      <webElementGuid>9b32ed06-7b33-4bcd-8747-3839584e0df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publikasi'])[3]/following::div[7]</value>
      <webElementGuid>acb699ed-f9ba-45ad-881c-e275ca54f86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Publikasi'])[2]/following::div[7]</value>
      <webElementGuid>87ef5af8-3d57-40a9-b24e-036363cf3711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I.  Tantangan global, Hibah Internasional dan LDKPI'])[1]/preceding::div[1]</value>
      <webElementGuid>84987f3c-0a3d-43d5-a1ac-e306dde286b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gini'])[1]/preceding::div[1]</value>
      <webElementGuid>72425b46-60fb-4ff8-a3e5-9121a3a1345c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Publikasi Ketiga']/parent::*</value>
      <webElementGuid>ad61780b-18ba-4b1b-9e56-3ff9de91e72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/a/div</value>
      <webElementGuid>a86dc801-c42b-4146-b470-eea27f652a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Publikasi Ketiga' or . = 'Publikasi Ketiga')]</value>
      <webElementGuid>8ae53250-92cf-4747-a82a-4717663d3922</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
