<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3b83e40c-590e-4e27-9178-d18a120fa1d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menuToggle']/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cffa879b-fe84-4552-978c-de08848ed891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sapadjppr.kemenkeu.go.id/file.php/50138PMBTYYAXGT50137319FCBD59/6117c759ed3d3_sapa_icon.png</value>
      <webElementGuid>c506b8e4-fa7e-4281-825a-96d861a5fdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuToggle&quot;)/li[@class=&quot;flex-grow&quot;]/a[1]/img[1]</value>
      <webElementGuid>9bf74de7-0b2d-4d88-b725-e82210005cbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menuToggle']/li/a/img</value>
      <webElementGuid>f47afac3-3780-4713-8d44-bba6d2ab63d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://sapadjppr.kemenkeu.go.id/file.php/50138PMBTYYAXGT50137319FCBD59/6117c759ed3d3_sapa_icon.png')]</value>
      <webElementGuid>b8210adb-f558-4ef1-bd3b-36f034256611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6fec98ea-eebe-4593-9c4c-d442612ba20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://sapadjppr.kemenkeu.go.id/file.php/50138PMBTYYAXGT50137319FCBD59/6117c759ed3d3_sapa_icon.png']</value>
      <webElementGuid>d11b57b7-ca54-435f-999f-98104ff1d080</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
