<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>0854e8ee-8c8e-4057-8e35-e187a5a5b8b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div[2]/div/div/video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>e6485fa4-bc0d-4553-bcb3-42be47ec12dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://10.201.79.218:1337/uploads/Video_Profile_Indonesian_AID_3_634c907827.mp4</value>
      <webElementGuid>13c1226e-992d-4fc4-9767-94fc275b4080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>8bd3d740-2ce0-4427-a4cd-db337acd3ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;video-player-container mt-4&quot;]/div[@class=&quot;video-wrapper&quot;]/div[@class=&quot;video-player&quot;]/div[@class=&quot;video-player&quot;]/video[1]</value>
      <webElementGuid>24579b41-2081-4bcf-b23d-b2d8f0c9db4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div/div/video</value>
      <webElementGuid>fe589e98-c25e-433c-be30-526ceba4c7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>de928397-53ae-4f0c-89b0-40e3eb7bd7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'http://10.201.79.218:1337/uploads/Video_Profile_Indonesian_AID_3_634c907827.mp4']</value>
      <webElementGuid>91990ebf-0a4c-4c1c-8ff3-02ac4b608721</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
