<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video</name>
   <tag></tag>
   <elementGuidId>bc8b96e0-e466-4d57-8641-cbfbbfaa42ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[3]/div[2]/div/div/video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>6f2c556f-f2d1-40ac-a287-2c5e26d9463a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://10.201.79.218:1337/uploads/Video_Profile_Indonesian_AID_3_634c907827.mp4</value>
      <webElementGuid>d4b76fe0-51fc-4d5e-9f8d-ecad3966e989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2108ba62-bb6a-4abf-905a-8d5065ba9406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App d-flex justify-content-center&quot;]/div[@class=&quot;video-player-container mt-4&quot;]/div[@class=&quot;video-wrapper&quot;]/div[@class=&quot;video-player&quot;]/div[@class=&quot;video-player&quot;]/video[1]</value>
      <webElementGuid>481a93a1-54d0-432b-a5fc-8d5b24eb735c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[3]/div[2]/div/div/video</value>
      <webElementGuid>e84bfae1-8397-4644-acc3-91a707678442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>a8204999-4cfd-4665-8a29-0c41134678b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@src = 'http://10.201.79.218:1337/uploads/Video_Profile_Indonesian_AID_3_634c907827.mp4']</value>
      <webElementGuid>83bc1d75-2c9c-4ecf-8f97-647a74545815</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
